### ISSUE TITLE
Fix url in the task Electricity Normalizer. 

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#210]
- In order to have correctly the ``#`` in the url of the node.

https://github.com/Gizra/negawatt-server/blob/master/negawatt/modules/custom/negawatt_normalizer/plugins/electricity_normalizer/ElectricityNormalizerBase.php#L579 

change for:
```php
'!meter_url' => l($wrapper->field_place_description->value(), '', array('fragment' => dashboard/marker/' . $node->nid)),
```

**Comment by shahardo** [comment]
Fixed on client
