### ISSUE TITLE
Don't hardcode the message arguments

### ISSUE THREAD

**Issue by amitaibu** [Gizra/negawatt-server#211]
Like this it's easier to change messages and their arguments.

https://github.com/capacity4dev/capacity4more/blob/develop/capacity4more/modules/c4m/message/c4m_message/c4m_message.module#L56-L77

and an example implementation - https://github.com/capacity4dev/capacity4more/blob/develop/capacity4more/modules/c4m/message/c4m_message/c4m_message.module#L182-L206

**Comment by shahardo** [comment]
Done
