### ISSUE TITLE
UI problems when too many markers are drawn

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#215]
When number of markers (leaflets) reaches ~150, strange thigns happen - map tiles are not allways shown, information panels disappear or are partially overwritten by map tilles.

![screenshot from 2014-12-23 15 00 59](https://cloud.githubusercontent.com/assets/4487099/5538025/ab7069f0-8ab4-11e4-996d-763ec84a14e1.png)

![screenshot from 2014-12-23 15 03 01](https://cloud.githubusercontent.com/assets/4487099/5538042/d67982a8-8ab4-11e4-87fa-44bf2ed50d13.png)

**Comment by shahardo** [comment]
Seems not to happen anymore.

**Comment by shahardo** [comment]
Still happens on Shahar'ss computer

**Comment by ceoaliongroo** [comment]
@shahardo could we close this one?

**Comment by shahardo** [comment]
There are still many UI problems on my computer. We have to figure out
first what is the source of the problem...
בתאריך 16 באפר' 2015 16:01,‏ "Carlos Mantilla" <notifications@github.com>
כתב:

**Comment by shahardo** [comment]
Problem was fixed after enabling hardware acceleration on the computer (for chrome):
- Go to: chrome://flags/
- Enable the first flag ("Override software rendering"):

See: http://www.webupd8.org/2014/01/enable-hardware-acceleration-in-chrome.html
