### ISSUE TITLE
blank screen on Firefox

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#245]
works ok on chrome, FF shows nothing:

![screen shot 2015-01-01 at 4 30 53 pm](https://cloud.githubusercontent.com/assets/1771/5592349/970ef172-91d3-11e4-87b0-597f2c8534b8.png)

**Comment by ceoaliongroo** [comment]
The error looks like about connection

Nir what firefox version? and what url?

I could open http://negawatt-dev.gizra.com/#/dashboard
![screen shot 2015-01-04 at 9 33 06 am](https://cloud.githubusercontent.com/assets/2622152/5605162/c610f434-93f4-11e4-9aa0-b44be7e12717.png)

And http://localhost:9000/#/dashboard
![screen shot 2015-01-04 at 9 33 12 am](https://cloud.githubusercontent.com/assets/2622152/5605163/ce09523a-93f4-11e4-89b4-0cda4aca5706.png)

![screen shot 2015-01-04 at 9 34 15 am](https://cloud.githubusercontent.com/assets/2622152/5605168/ea93761a-93f4-11e4-9d4f-ff7d7141d9b8.png)

**Comment by niryariv** [comment]
yep, i guess it just took a long time to load so I thought it's not working. closing for #246
