### ISSUE TITLE
Define style for active category

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#257]
@kerensoref, @niryariv  could you do a style to show the active category?

actually , i changed the fonts color to red. 

![screen shot 2015-01-05 at 4 15 47 pm](https://cloud.githubusercontent.com/assets/2622152/5614118/3f712982-94f6-11e4-9246-345e8347fa1f.png)

**Comment by kerensoref** [comment]
Color change is the best solution, but the red looks like an error.
I suggest: #26858d

**Comment by ceoaliongroo** [comment]
Thanks, i'll change the color.

**Comment by ceoaliongroo** [comment]
Look like confusing if we have 3 level of items.

![screen shot 2015-01-06 at 9 33 06 am](https://cloud.githubusercontent.com/assets/2622152/5625626/7cba4a8a-9587-11e4-94c4-b9fdc0677599.png)

@kerensoref, what do you suggest?

**Comment by kerensoref** [comment]
Yes, it's not looking great...
Try a gray one: #3e3e3e
And also, please change the font to Alef.

**Comment by kerensoref** [comment]
![negawatt hp7_3](https://cloud.githubusercontent.com/assets/7893274/5626129/b8a07fda-958f-11e4-982d-88fdcdf571ee.jpg)

**Comment by amitaibu** [comment]
@kerensoref in the app we have the number of markers next to each category. Can you update the design accordingly?

![define_style_for_active_category_ _issue__257_ _gizra_negawatt-server](https://cloud.githubusercontent.com/assets/125707/5626219/5d606408-9591-11e4-8eba-c56eb3268fb4.jpg)

**Comment by ceoaliongroo** [comment]
I changed the font family and the color to the level/depth 3 of category. @kerensoref, looks ok?

![screen shot 2015-01-06 at 10 55 42 am](https://cloud.githubusercontent.com/assets/2622152/5626357/08d7cec4-9593-11e4-8d15-4da2bc7ec694.png)
![screen shot 2015-01-06 at 10 50 55 am](https://cloud.githubusercontent.com/assets/2622152/5626358/08dfea6e-9593-11e4-8a7f-037b3a9b93b1.png)

**Comment by kerensoref** [comment]
Attached. Please add more space between the lines of the text.
![negawatt hp8](https://cloud.githubusercontent.com/assets/7893274/5627190/b52f8b12-959d-11e4-9cb5-29eb6383e605.jpg)

**Comment by ceoaliongroo** [comment]
@kerensoref after the changes, looks like this way:
![screen shot 2015-01-06 at 1 29 43 pm](https://cloud.githubusercontent.com/assets/2622152/5628034/145f46de-95aa-11e4-953d-a8ab57419347.png)

**Comment by kerensoref** [comment]
The font is great, the color is still not correct. 
First level - 2c2c2c, Second level - 3e3e3e Third looks good.
Can we use that Pin icon?
https://www.dropbox.com/s/n51egkzz847f80q/pin.png?dl=0

**Comment by ceoaliongroo** [comment]
Ok i'll change the colors.
_Could send also the pin selected too?
In PNG and SVG format

thanks

**Comment by kerensoref** [comment]
https://www.dropbox.com/sh/ccc202joc10fl0j/AABTBIE1_8-OAEKHxSX8NQWAa?dl=0

**Comment by kerensoref** [comment]
No, don't want to overload...

**Comment by ceoaliongroo** [comment]
Done.
