### ISSUE TITLE
Add GUI to select chart time-frame

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#265]
like this?
![screenshot from 2015-01-07 10 59 47](https://cloud.githubusercontent.com/assets/4487099/5643136/34807a42-965d-11e4-8b03-ea56b0beebc4.png)
See:
https://developers.google.com/chart/interactive/docs/gallery/annotationchart

**Comment by ceoaliongroo** [comment]
- [ ] add annotation option

**Comment by shahardo** [comment]
Closed
