### ISSUE TITLE
Add multi account to `anomalous_consumption` resource.

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#271]
http://localhost/negawatt-server/www/api/v1.0/anomalous_consumption

**Comment by ceoaliongroo** [comment]
@shahardo, message have to be categorized by account?

**Comment by amitaibu** [comment]
Yes they should reference the group

‫ב-13 בינו 2015, בשעה 17:00, ‏Carlos Mantilla <notifications@github.com> כתב/ה:‬

**Comment by shahardo** [comment]
Closed in favor of #304
