### ISSUE TITLE
Provide  'time of frequency' to chart totals electricity data

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#290]
Provide resource for account entity to know the 'time of frequency' available to chart electricity data, this is need it to build the option in the chart.

![screen shot 2015-01-25 at 11 29 22 am](https://cloud.githubusercontent.com/assets/2622152/5891030/03979b7c-a486-11e4-8b27-215b98650910.png)

**Comment by ceoaliongroo** [comment]
Related #234

**Comment by shahardo** [comment]
Done on #289
