### ISSUE TITLE
Each scenario need delete token from session, before login again.

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#332]
![screen shot 2015-02-03 at 4 01 18 pm](https://cloud.githubusercontent.com/assets/2622152/6021413/51b33b74-abbe-11e4-8206-e878c5288fc1.png)

**Comment by amitaibu** [comment]
This is already [happening](https://github.com/Gizra/negawatt-server/blob/master/behat/features/bootstrap/FeatureContext.php#L106-L107)

**Comment by ceoaliongroo** [comment]
Yes on the server side (database), the client side still have the token in the localstorage as [login return 401](https://github.com/Gizra/negawatt-server/blob/master/client/app/scripts/services/auth.js#L13-L23)

**Comment by amitaibu** [comment]
In that case the ``Given I login ..``, should visit a new ``/#/user/logout`` route that will clear the token

**Comment by ceoaliongroo** [comment]
working on it.

**Comment by ceoaliongroo** [comment]
Done. PR #331
