### ISSUE TITLE
When selecting a meter or a category, the checkboxes disappear.

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#384]
Checkboxes appear only on 'dashboard.withAccount' state

**Comment by ceoaliongroo** [comment]
It's necessary define how the checkboxes will be works when select a category.
- What is the behaviour of the markers of the category unselected?. Will re-appear in the map, breaking the category filter logic, already implemented? 
- Reduce the checkboxes only to the children of the selected Category?

**Comment by ceoaliongroo** [comment]
Done
