### ISSUE TITLE
On narrow window, the ruler elements create another line below the ruler

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#435]
On a window narrower than 700px, elements from the ruler - like logo and weather - create a new line of ruler elements below the ruler itself. They 'hide' the elements beneath them and prevent mouse clicks:
![screenshot](https://cloud.githubusercontent.com/assets/4487099/7002977/a71bf9ca-dc5b-11e4-9c63-b584193d9f29.jpg)

**Comment by ceoaliongroo** [comment]
Done.
