### ISSUE TITLE
Error HTTP 510 in the Weather directive.

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#462]
- [x] Remove directive. 

https://openweathermap.desk.com/customer/portal/questions/9787798-what-exactly-is-server-error-51-

**Comment by amitaibu** [comment]
This isn't needed for now, as we should remove the directive

**Comment by ceoaliongroo** [comment]
Ok, just leaving note in issues.

**Comment by ceoaliongroo** [comment]
Done.
