### ISSUE TITLE
Usage chart disappears

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#478]
To reproduce:
- Log as carlos
- Go to astral (dashboard/2)
- Click on category - either first or second level. see that the usage chart disappears.

If changing chart frequency to month, the chart will re-appear, but changing back to day, hour or minute, will hide it again.

**Comment by ceoaliongroo** [comment]
Works in Eilat dashboard 7.

![screen shot 2015-06-04 at 8 15 57 pm](https://cloud.githubusercontent.com/assets/2622152/7990006/89fee1e4-0af6-11e5-9dd9-face196d55bb.png)

@shahardo is need it to check the data for astral, actually look empty.

Done.
