### ISSUE TITLE
Login stucks when there're no meters.

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#492]
Reproduce:
- Build server with no meters on account 1 (kiryat gat)
- Try to login.

**Comment by shahardo** [comment]
Also:
- Build server with no meters on account 1, but has meters on account 2 (astral)
- Try to login to astral - somehow it tries to read the meters of account 1 and gets stuck.

**Comment by ceoaliongroo** [comment]
@shahardo, @niryariv, @amitaibu 

- Have sense have an account with out meters?
- I propose a new feature to select via Drupal administrator, witch one is the default account if the user have multiple accounts. Have sense for you?

**Comment by shahardo** [comment]
Thtat's a good idea. Also to have some GUI functionality to switch between
accounts if the user has more then one.
However, it might happen that there is an account without any meters (e.g.,
an account was just created and no meters were imported yet), and we should
make sure it will not stop the application.

**Comment by ceoaliongroo** [comment]
@shahardo It's possible that have also no categories?

![screen shot 2015-04-26 at 1 15 59 pm](https://cloud.githubusercontent.com/assets/2622152/7336771/707da696-ec16-11e4-8abe-4f2c26fe483d.png)

**Comment by ceoaliongroo** [comment]
Actually the categories are show only if have meters. If does not have meters, no categories are show

It's what you expect to see when there is not meters?
![screen shot 2015-04-26 at 1 37 54 pm](https://cloud.githubusercontent.com/assets/2622152/7336855/98cd1368-ec19-11e4-964c-2f0513ec20f2.png)

**Comment by ceoaliongroo** [comment]
Done.
