### ISSUE TITLE
code and serial # are always 0

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#518]
![screen shot 2015-04-30 at 2 32 44 pm](https://cloud.githubusercontent.com/assets/1771/7411943/e9f0972c-ef45-11e4-93f2-70415880d110.png)

**Comment by shahardo** [comment]
@niryariv , the problem is with the temp data we have - it has zeros for all the meters. Soon I will use the scraper to load real data set that will hold real meter id's

**Comment by shahardo** [comment]
Doesn't happen for real scraper data.
