### ISSUE TITLE
no yearly graph

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#519]
for example in kiryat gat we do have data for several years' back, why not show it in the graph?

![screen shot 2015-04-30 at 2 34 44 pm](https://cloud.githubusercontent.com/assets/1771/7411959/13e8b384-ef46-11e4-9f51-3a6cd31b7645.png)

**Comment by ceoaliongroo** [comment]
We have PR #589 with a refactor of the usage chart component. 


@shahardo, you could do the data checking to close this issue?

thanks

**Comment by shahardo** [comment]
Doesn't happen with real data.
