### ISSUE TITLE
Time waiting from server response (TTFB) of API electricity end point from the server is to long

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#544]
![screen shot 2015-05-14 at 7 22 27 pm](https://cloud.githubusercontent.com/assets/2622152/7676248/2acf0528-fd4a-11e4-9c98-a10e099d9647.png)
![screen shot 2015-05-14 at 5 55 51 pm](https://cloud.githubusercontent.com/assets/2622152/7676249/2acfd494-fd4a-11e4-893f-e894aa2fce3a.png)
![screen shot 2015-05-14 at 5 55 45 pm](https://cloud.githubusercontent.com/assets/2622152/7676247/2acce55e-fd4a-11e4-8f7b-79d08c1f87dc.png)

**Comment by ceoaliongroo** [comment]
The restful query:
http://localhost/negawatt-server/www/api/electricity?filter%5Bmeter_account%5D=1&filter%5Btimestamp%5D%5Boperator%5D=BETWEEN&filter%5Btimestamp%5D%5Bvalue%5D%5B0%5D=1368973989&filter%5Btimestamp%5D%5Bvalue%5D%5B1%5D=1432045989&filter%5Btype%5D=2&page=2

Disabeling ``$this->prepareSummary();`` at ``NegawattElectricityResource.class.php`` will remove the wait.
https://github.com/Gizra/negawatt-server/blob/master/negawatt/modules/custom/negawatt_restful/plugins/restful/electricity/1.0/NegawattElectricityResource.class.php#L337

**Comment by shahardo** [comment]
Fixed
