### ISSUE TITLE
Increase zoom in map

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#559]
When putting street-light poles on the map, even in the max zoom, the markers are too dense:
![screenshot from 2015-06-02 09 34 38](https://cloud.githubusercontent.com/assets/4487099/7929801/cc3f370e-090a-11e5-8d9b-4ce876c445b1.png)
It should be possible to increase the zoom level.

**Comment by ceoaliongroo** [comment]
Done.
