### ISSUE TITLE
Define get limits and period to request the electricity 

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#566]
For each request, need ask min and max limit before to get real data.

We pass a start parameter `nodata=1` in the electricity request, to get the configuration (``summary`` data only)

**Comment by shahardo** [comment]
@ceoaliongroo is this issue fixed?

**Comment by ceoaliongroo** [comment]
Keep open until some PR related will be merge

**Comment by ceoaliongroo** [comment]
Related PR #589

**Comment by ceoaliongroo** [comment]
Done.
