### ISSUE TITLE
Timestamp limits `null` when select meter

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#570]
``http://localhost/negawatt-server/www/api/electricity?filter%5Bfrequency%5D=5&filter%5Bmeter%5D%5Boperator%5D=IN&filter%5Bmeter%5D%5Bvalue%5D%5B0%5D=184&filter%5Bmeter_account%5D=1&nodata=1&page=1``

Related #566

![screen shot 2015-06-07 at 11 39 40 am](https://cloud.githubusercontent.com/assets/2622152/8023236/6033d944-0d0a-11e5-85af-1e1dc6f78391.png)
![screen shot 2015-06-07 at 11 39 14 am](https://cloud.githubusercontent.com/assets/2622152/8023237/60348592-0d0a-11e5-84aa-90c66dbefc47.png)

**Comment by shahardo** [comment]
Non an issue. This is normal behavior of "dead" meters.
