### ISSUE TITLE
Summary values empty when select a meter - electricity end point. 

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#571]
![screen shot 2015-06-07 at 11 39 14 am](https://cloud.githubusercontent.com/assets/2622152/8023244/b2d6d9e4-0d0a-11e5-9ea4-aad8b0f7a0b6.png)

**Comment by ceoaliongroo** [comment]
Related:  #537

**Comment by shahardo** [comment]
Not an issue. This is normal behavior for "dead" meters.

**Comment by ceoaliongroo** [comment]
Related https://github.com/Gizra/negawatt-server/issues/572
