### ISSUE TITLE
Create end point to get meter by id

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#576]
``http://localhost/negawatt-server/www/api/meters/73``
or
``http://localhost/negawatt-server/www/api/meters/?filter[id]=73``
 
Actually is not possible
![screen shot 2015-06-10 at 5 59 53 pm](https://cloud.githubusercontent.com/assets/2622152/8085777/8ce4f454-0f9a-11e5-98eb-b719f1fc8e58.png)
![screen shot 2015-06-10 at 5 58 32 pm](https://cloud.githubusercontent.com/assets/2622152/8085778/8ce616f4-0f9a-11e5-951c-d8c4d1678457.png)

this make electricity implementation for ``dead meters`` difficult

![screen shot 2015-06-10 at 5 56 26 pm](https://cloud.githubusercontent.com/assets/2622152/8085776/8ce48f3c-0f9a-11e5-8483-88e2d9f8f362.png)

**Comment by shahardo** [comment]
Done.
Use .../api/meters/<id>
