### ISSUE TITLE
reset the map to initial coords/zoom when clicking home

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#581]

**Comment by ceoaliongroo** [comment]
@niryariv, @shahardo  if we have define the limits #555, maybe a __button__ to recenter and reset the zoom. 

![screen shot 2015-06-15 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/2622152/8158105/bba49b84-1362-11e5-8b12-7e45b411c769.png)

Could be more intuitive to the user?

**Comment by ceoaliongroo** [comment]
Close, in favor #555
