### ISSUE TITLE
Show the messages in order Descendent (newest ones first, oldest last)

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#659]
![other-asc](https://cloud.githubusercontent.com/assets/2622152/8525346/f73f74d2-2408-11e5-8fb1-59778e4b7067.png)

**Comment by shahardo** [comment]
sort=-timestamp
​

**Comment by ceoaliongroo** [comment]
@shahardo , `sort=-timestamp` is a parameter for the URL request?

**Comment by shahardo** [comment]
yes. as I saw, it's already there....
​
