### ISSUE TITLE
Selected meter stop change the color 

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/negawatt-server#662]
![screen shot 2015-07-06 at 6 08 46 pm](https://cloud.githubusercontent.com/assets/2622152/8525555/3a57d6be-240a-11e5-99a2-ee89cf377eda.png)

**Comment by shahardo** [comment]
Can't see the difference
​

**Comment by ceoaliongroo** [comment]
relate with #652

**Comment by ceoaliongroo** [comment]
Retested master, looks like the this error appear in the change of branch #654 (PR #657)

**Comment by ceoaliongroo** [comment]
Done.
