### ISSUE TITLE
When selecting a category, not all related markers remain solid

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#681]
Example:
- log into eilat
- select category גן ילדים
- see that גן פיראן ימית is transparent, although it belongs to the category:
![mozilla firefox_001](https://cloud.githubusercontent.com/assets/4487099/8645102/1eb3ac4c-294d-11e5-8d1a-827fd47d35b4.png)

**Comment by ceoaliongroo** [comment]
@shahardo 

__data:__ [name of database of database file from "negawatt-data" to reproduce the error in dev]

**Comment by shahardo** [comment]
the usual: negawatt-data/unified/dump
​

**Comment by ceoaliongroo** [comment]
Is this folder?
https://github.com/Gizra/negawatt-data/tree/master/sql-migrate-unified
and there many fiales with the word `dump`

**Comment by shahardo** [comment]
The shortest one: dump.sql.tar.gz
<https://github.com/Gizra/negawatt-data/blob/master/sql-migrate-unified/dump.sql.tar.gz>
 :-)
​

**Comment by ceoaliongroo** [comment]
thanks

**Comment by ceoaliongroo** [comment]
Done.
