### ISSUE TITLE
negawatt.gizra.com doesn't work

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#684]
When trying to login, message: "אין חיבור לשרת" appears:

![mozilla firefox_004](https://cloud.githubusercontent.com/assets/4487099/8645557/171fa5a4-2951-11e5-8110-1583c3758ffc.png)

**Comment by ceoaliongroo** [comment]
@shahardo, please add

__enviroment:__
__data:__
__how to reproduce:__

**Comment by niryariv** [comment]
@ceoaliongroo - perhaps it's breaking on the server side?
![screen shot 2015-07-13 at 1 54 05 pm](https://cloud.githubusercontent.com/assets/1771/8648117/a9ae5d6a-2966-11e5-952d-fe9030d9f1e5.png)

**Comment by ceoaliongroo** [comment]
I think is related with the deploy, possible the config flles of the client.  Is not possible to do a simple clone of enviroment, need to make son configuration. 

I'm working on this

**Comment by ceoaliongroo** [comment]
Looks related with the last clone, it was an error in master on the morning
![screen shot 2015-07-13 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/2622152/8648728/bae11cee-296b-11e5-82a4-06f58c7b977d.png)

i trying redeploy

**Comment by shahardo** [comment]
Fixed
