### ISSUE TITLE
Missing site description in messages

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#685]
![mozilla firefox_005](https://cloud.githubusercontent.com/assets/4487099/8645609/8f8dfc8e-2951-11e5-8149-959ca245f2ab.png)

Fix:
- [x] Modify notifications API to include site title and address.
- [ ] Modify client app: if there's no site description, show the title, if there's no title, shor the address

**Comment by shahardo** [comment]
@ceoaliongroo I rebuilt the database to include the new message fields. It's now in the default database dump: negawatt-data/sql-migrate-unified/dump.sql.tar.gz. Your turn now...

**Comment by ceoaliongroo** [comment]
geat!

**Comment by shahardo** [comment]
Fixed
