### ISSUE TITLE
Astral has "other" meter category (perhaps the satecs?)

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#689]
![screen shot 2015-07-13 at 5 34 37 pm](https://cloud.githubusercontent.com/assets/1771/8652100/828d3930-2985-11e5-962f-69c24750a3ff.png)

**Comment by shahardo** [comment]
It's not the satec's, but IEC meters without proper names.
The SATECs are מטבח, מיזוג 1, מיזוג 2
​
