### ISSUE TITLE
Fix usage chart titles

### ISSUE THREAD

**Issue by shahardo** [Gizra/negawatt-server#700]
- [x] Add chart title: name of marker, date:

![selection_011](https://cloud.githubusercontent.com/assets/4487099/8723322/7082fdc2-2bd5-11e5-8e08-90dd8785c025.png)

- [x] Fix x-axis titles

![selection_012](https://cloud.githubusercontent.com/assets/4487099/8723341/9074bd50-2bd5-11e5-89e4-ea3be6a4ef2d.png)

**Comment by bitamar** [comment]
Date will be added in #721

**Comment by niryariv** [comment]
@bitamar can this be closed?
