### ISSUE TITLE
use different chart titles

### ISSUE THREAD

**Issue by niryariv** [Gizra/negawatt-server#733]
currently we use the meter name ("1232341-12954398") - why not use "[place]-[address]" like in the pop ups?
@shahardo what do u think?

![screen shot 2015-07-23 at 9 49 17 am](https://cloud.githubusercontent.com/assets/1771/8844703/a1a106a6-3120-11e5-8da6-c2c295c22505.png)

**Comment by shahardo** [comment]
@bitamar is working on that in #726
