### ISSUE TITLE
New chart view design

### ISSUE THREAD

**Issue by bitamar** [Gizra/negawatt-server#754]
<img width="1301" alt="screen shot 2015-07-29 at 14 10 39" src="https://cloud.githubusercontent.com/assets/2283680/8956155/b17ef2f6-35fb-11e5-842c-ac7a25069164.png">

**Comment by bitamar** [comment]
<img width="1236" alt="screen shot 2015-08-02 at 16 07 36" src="https://cloud.githubusercontent.com/assets/2283680/9026244/070e9072-3931-11e5-9d04-481d2250cbbc.png">

@shahardo - See updated version

**Comment by shahardo** [comment]
Done
